### ISSUE TITLE
#2 각 메뉴 항목 정리 

### ISSUE THREAD

**Issue by 001xm** [jsmssu/seniorfit#2]
## 다른 프로그램하기
1. 하루 운동_1d : 2시간, 주2회이하 
2. 주5회운동_w5 : 1시간반,주5회
3. 주3회운동_w3 : 1시간반,주3회
4. 준비운동_a : 15분, 매일(운동 전)
5. 정리운동_f : 15분, 매일(운동 후)
6. 근력강화_b : 25분, 주2-3회
7. 심폐 지구력 강화_c : 45분, 주2-3회
8. 유연성강화_d : 15분, 주2-3회
9. 평행성/체력강화_e : 25분, 주2-3회
## 나만의 운동하기
1. 준비운동 a
   - 준비운동 a_1
2. 정리운동 f 
   - 정리운동 f_1
3. 근력강화 b
   - 수건비비기 b_1
   - 옆구리운동 b_2
   - 양팔휘돌리기 b_3
   - 다리펴기 b_4 
   - 양손당기기 b_5
4. 심폐 지구력 강화  c
   - 팔들고숨쉬기 c_1
   - 다리올리며숨쉬기 c_2
   - 무릎구부리며 숨쉬기 c_3
   - 가슴벌리며숨쉬기 c_4
   - 팔들어내리며숨쉬기 c_5
5. 유연성강화 d
   - 이불위체조 d_1
   - 앉아무릎누르기 d_2
   - 앉아발끝닿기 d_3
   - 발목돌리기 d_4
   - 장딴지펴기 d_5
6. 평행성/체력강화 e
   - 외발서기 e_1
   - 팔멀리뻗기 e_2 
   - 풍선쳐올리기기 e_3

**Comment by jsmssu** [comment]
적용
